In [2]:
import numpy as np

In [2]:
a = np.array([4,10,12,23,-2,-1,0,0,0,-6,3,-7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [5]:
#How many negative numbers are there?
a[a < 0]
a[a < 0].shape

array([-2, -1, -6, -7])

In [8]:
#How many positive numbers are there?
a[a > 0]
a[a > 0].shape

(5,)

In [10]:
#How many even positive numbers are there?
a[(a % 2 == 0) & (a > 0)]
a[(a % 2 == 0) & (a > 0)].shape

(3,)

In [16]:
#If you were to add 3 to each data point, how many 
#positive numbers would there be?
a3 = a + 3
a[a3>0].shape

(10,)

In [19]:
#If you squared each number, what would the new mean 
#and standard deviation be?
asquared = a ** 2
asquared.mean()
asquared.std()

144.0243035046516

In [25]:
#A common statistical operation on a dataset is centering. 
#This means to adjust the data such that the center of the 
#data is at 0. This is done by subtracting the mean from 
#each data point. Center the data set.
a.mean()
a - 3

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [27]:
#Calculate the z-score for each data point. Recall that the 
#z-score is given by:
za = a - a.mean()
za / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [4]:
#More Numpy Practice
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all 
#the numbers in above list
sum_of_a = sum(a)
print(sum_of_a)


a_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
sum_of_a1 = a_array.sum()
print(sum_of_a1)

55
55


In [52]:
#2 Exercise 2 - Make a variable named min_of_a to hold the minimum 
#of all the numbers in the above list
min_of_a = min(a)
print(min_of_a)

min_of_a1 = a_array.min()
print(min_of_a1)

1
1


In [53]:
# Exercise 3 - Make a variable named max_of_a to hold the max
#number of all the numbers in the above list
max_of_a = max(a)
print(max_of_a)

max_of_a1 = a_array.max()
print(max_of_a1)


10
10


In [55]:
# Exercise 4 - Make a variable named mean_of_a to hold the average 
#of all the numbers in the above list
n = len(a)
mean_of_a = sum(a) / n
print(mean_of_a)

mean_of_a1 = a_array.mean()
print(mean_of_a1)


5.5
5.5


In [8]:
# Exercise 5 - Make a variable named product_of_a to hold the 
#product of multiplying all the numbers in the above list together
h = 1
for x in a:
    h = h * x
product_of_a = h
print(product_of_a)

product_of_a1 = np.prod(a_array)
print(product_of_a1)

3628800
3628800


In [18]:
# Exercise 6 - Make a variable named squares_of_a. It should hold 
#each number in a squared like [1, 4, 9, 16, 25...]
s = [x ** 2 for x in a]
squares_of_a = s
print(squares_of_a)

squares_of_a1 = [x**2 for x in a]
squares_of_a1

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [31]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only 
#the odd numbers
odds_in_a = [num for num in a if num % 2 != 0]
print(odds_in_a)

odds_in_a1 = a_array[a_array % 2 == 1]
print(odds_in_a1)


[1, 3, 5, 7, 9]
[1 3 5 7 9]


In [32]:
# Exercise 8 - Make a variable named evens_in_a. It should hold 
#only the evens.
evens_in_a = [num for num in a if num % 2 == 0]
print(evens_in_a)

evens_in_a1 = a_array[a_array % 2 == 0]
print(evens_in_a1)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


In [38]:
# Setup 2: Consider what it would take to find the sum, min, max, 
#average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b1 = np.array(
    [
    [3, 4, 5],
    [6, 7, 8]
])
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as 
#the variable. **Hint, you'll first need to make sure that the "b" 
#variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
print(sum_of_b)

sum_of_b1 = b1.sum()
print(sum_of_b1)

33
33


In [41]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
print(min_of_b)

min_of_b1 = np.min(b1)
print(min_of_b1)

3
3


In [42]:
# Exercise 3 - refactor the following maximum calculation to find the 
#answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
print(max_of_b)

max_of_b1 = np.max(b1)
print(max_of_b)

8
8


In [47]:
# Exercise 4 - refactor the following using numpy to find the mean of 
#b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
print(mean_of_b)

mean_of_b1 = (sum(b1[0]) + sum(b1[1])) / (len(b1[0]) + len(b1[1]))
print(mean_of_b1)

5.5
5.5


In [52]:
# Exercise 5 - refactor the following to use numpy for calculating 
#the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
print(product_of_b)

product_of_b1 = np.prod(b1)
print(product_of_b1)

20160
20160


In [54]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
print(squares_of_b)

squares_of_b1 = np.square(b1)
print(squares_of_b1)

[9, 16, 25, 36, 49, 64]
[[ 9 16 25]
 [36 49 64]]


In [56]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
print(odds_in_b)

odds_in_b1 = b1[b1 % 2 != 0]
print(odds_in_b1)

[3, 5, 7]
[3 5 7]


In [58]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
print(evens_in_b)

evens_in_b1 = b1[b1 % 2 == 0]
print(evens_in_b1)

[4, 6, 8]
[4 6 8]


In [59]:
# Exercise 9 - print out the shape of the array b.
b1.shape

(2, 3)